#10.4. API da Rapi-Dex com WireMock - 50"
services:
  rapidexapi:
    image: wiremock/wiremock:3x
    ports:
      - "8780:8080"
    volumes:
      - ./etc/wiremock:/home/wiremock/mappings
    command: --verbose --disable-http2-plain  #10.5. Integração com Spring RestClient - 15' o erro que ocorre na aula o Alex resolve adicionando --disable-hhtp2-plain, mas no meu código não adicionei e funcionou mesmo assim